
GET http://localhost:4400/api/v1/test HTTP/1.1
Content-Type: application/json
### 
GET http://localhost:4400/ HTTP/1.1
Content-Type: application/json
### Get one user
GET http://localhost:4400/api/v1/users/2 HTTP/1.1
Content-Type: application/json
### Get all users
GET http://localhost:4400/api/v1/users/ HTTP/1.1
Content-Type: application/json
### Creating a new user
POST http://localhost:4400/api/v1/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Perez",
    "email": "juancito@gmail.com",
    "username": "JHon",
    "password": "supersecreto"
}
### Update a new user
PUT http://localhost:4400/api/v1/users/1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ethan",
    "lastName": "Winters",
    "email": "winterRE4@gmail.com",
    "username": "EthWin"
}
### Delete a new user
DELETE  http://localhost:4400/api/v1/users/7 HTTP/1.1
Content-Type: application/json
### Get all tasks
GET http://localhost:4400/api/v1/boards/ HTTP/1.1
Content-Type: application/json
### Creating a new task
POST http://localhost:4400/api/v1/boards/ HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "boardName": "Bootcamp",
    "backgroundColor": "#f02d3e"
}