
GET http://localhost:4400/api/v1/test HTTP/1.1
Content-Type: application/json
### 
GET http://localhost:4400/ HTTP/1.1
Content-Type: application/json
### Get one user
GET http://localhost:4400/api/v1/account HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJleHAiOjE2MjEwNDc3OTUsImlzcyI6Im15QmFja2VuZCJ9.QobRgceB-EbqlHkLhhG7itHXBiH1INHQ_RsnBgCJ9NQ

### Get all users
GET http://localhost:4400/api/v1/users/ HTTP/1.1
Content-Type: application/json
### Creating a new user
POST http://localhost:4400/api/v1/account/signup HTTP/1.1
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Martinez",
    "email": "lkezhn@gmail.com",
    "username": "LKez",
    "password": "password"
}
### Update a new user
PUT http://localhost:4400/api/v1/users/1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ethan",
    "lastName": "Winters",
    "email": "winterRE4@gmail.com",
    "username": "EthWin"
}
### Delete a new user
DELETE  http://localhost:4400/api/v1/users/7 HTTP/1.1
Content-Type: application/json
### Get all boards
GET http://localhost:4400/api/v1/boards/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJleHAiOjE2MjEyNjkzMjQsImlzcyI6Im15QmFja2VuZCJ9.U9Bq4vxLQQ2uJTevXF6XajkWgTvZcMb8SZKYPe6G47c

### Get board's members
GET http://localhost:4400/api/v1/boards/4/members HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJleHAiOjE2MjEyNjkzMjQsImlzcyI6Im15QmFja2VuZCJ9.U9Bq4vxLQQ2uJTevXF6XajkWgTvZcMb8SZKYPe6G47c

### Creating a new board
POST http://localhost:4400/api/v1/boards/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJleHAiOjE2MjEyNjc1MDcsImlzcyI6Im15QmFja2VuZCJ9.VPaxBzk4PhgOEBAxztnsn2AyJWHGSrYkoaOSxdyyCcU

{
    "boardName": "Algoritmos",
    "backgroundColor": "blue"
}
### Login
POST http://localhost:4400/api/v1/account/login HTTP/1.1
Content-Type: application/json

{
    "userName": "LKez",
    "password": "password"
}
