DROP DATABASE IF EXISTS Trill;

CREATE DATABASE Trill CHARACTER SET utf8;

USE Trill;

CREATE TABLE User(
    id INT AUTO_INCREMENT PRIMARY KEY,
    str_firstName VARCHAR(100) NOT NULL,
    str_lastName VARCHAR(100) NOT NULL,
    str_email VARCHAR(60) NOT NULL,
    str_username VARCHAR(16) NOT NULL,
    str_password VARCHAR(100) NOT NULL
);
